# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  use_frameworks!

  pod 'DDUtil', '0.2.5'

end
